[package]
name = "fidryn-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Incremental compile and evaluate driver"

[dependencies]
blake3.workspace = true
fidryn-check.workspace = true
fidryn-core.workspace = true
fidryn-eval.workspace = true
fidryn-handlers.workspace = true
fidryn-hir.workspace = true
fidryn-syntax.workspace = true
salsa.workspace = true
serde_json.workspace = true
